import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/material-tailwind";
import Navbar from "@/components/navbar";
import Main from "@/components/main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-[#f5f5f5]">
        <ThemeProvider>
          <Navbar />
          <Main>{children}</Main>
        </ThemeProvider>
      </body>
    </html>
  );
}
